version: "3.9"

services:
  app:
    build: library-tracker
    hostname: library-tracker
    container_name: library-app
    ports:
      - 5173:5173
    volumes:
      - ./library-tracker:/code/library-tracker:cached
    depends_on:
      - db
      - redis
    networks:
      - library-network

  nginx:
    image: nginx:stable
    container_name: library-nginx
    ports:
      - "8080:80"
    volumes:
      - ./library-tracker:/code/library-tracker
      - ./library-tracker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - library-network

  db:
    image: mysql:8.0.39
    container_name: library-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library_db
      MYSQL_USER: library_user
      MYSQL_PASSWORD: library_pass
    ports:
      - 33075:3306
    volumes:
      - mysql_volume:/var/lib/mysql
    networks:
      - library-network

  redis:
    image: redis:7
    container_name: library-redis
    ports:
      - 7050:6379
    networks:
      - library-network

volumes:
  mysql_volume:

networks:
  library-network:  